import type { Theme } from "../types.js";

export const gruvbox: Theme = {
  name: "gruvbox",
  displayName: "Gruvbox Dark",
  description: "Retro groove color scheme with warm earthy tones",
  author: "morhetz",
  variant: "dark",
  colors: {
    background: "#282828",
    foreground: "#ebdbb2",
    cursor: "#ebdbb2",
    selectionBackground: "#504945",
    selectionForeground: "#ebdbb2",
    black: "#282828",
    red: "#cc241d",
    green: "#98971a",
    yellow: "#d79921",
    blue: "#458588",
    magenta: "#b16286",
    cyan: "#689d6a",
    white: "#a89984",
    brightBlack: "#928374",
    brightRed: "#fb4934",
    brightGreen: "#b8bb26",
    brightYellow: "#fabd2f",
    brightBlue: "#83a598",
    brightMagenta: "#d3869b",
    brightCyan: "#8ec07c",
    brightWhite: "#ebdbb2",
  },
  appearance: {
    backgroundOpacity: 0.92,
    backgroundBlur: 15,
    cursorStyle: "block",
    cursorBlink: false,
  },
};
