import type { Theme } from "../types.js";

export const tokyoNight: Theme = {
  name: "tokyo-night",
  displayName: "Tokyo Night",
  description: "Clean dark theme inspired by Tokyo city lights",
  author: "Enkia",
  variant: "dark",
  colors: {
    background: "#1a1b26",
    foreground: "#c0caf5",
    cursor: "#c0caf5",
    selectionBackground: "#33467c",
    selectionForeground: "#c0caf5",
    black: "#15161e",
    red: "#f7768e",
    green: "#9ece6a",
    yellow: "#e0af68",
    blue: "#7aa2f7",
    magenta: "#bb9af7",
    cyan: "#7dcfff",
    white: "#a9b1d6",
    brightBlack: "#414868",
    brightRed: "#f7768e",
    brightGreen: "#9ece6a",
    brightYellow: "#e0af68",
    brightBlue: "#7aa2f7",
    brightMagenta: "#bb9af7",
    brightCyan: "#7dcfff",
    brightWhite: "#c0caf5",
  },
  appearance: {
    backgroundOpacity: 0.88,
    backgroundBlur: 25,
    cursorStyle: "bar",
    cursorBlink: true,
  },
};
