import type { Theme } from "../../types.js";

interface AlacrittyConfig {
  readonly font: { readonly normal: { readonly family: string }; readonly size: number };
  readonly window: {
    readonly opacity: number;
    readonly blur: boolean;
    readonly padding: { readonly x: number; readonly y: number };
    readonly decorations: string;
  };
  readonly cursor: {
    readonly style: { readonly shape: string; readonly blinking: string };
  };
  readonly colors: {
    readonly primary: { readonly background: string; readonly foreground: string };
    readonly cursor: { readonly text: string; readonly cursor: string };
    readonly selection: { readonly text: string; readonly background: string };
    readonly normal: Record<string, string>;
    readonly bright: Record<string, string>;
  };
  readonly scrolling: { readonly history: number };
}

export function generateAlacrittyConfig(theme: Theme): string {
  const { colors, appearance } = theme;

  const cursorShape =
    appearance.cursorStyle === "bar"
      ? "Beam"
      : appearance.cursorStyle === "underline"
        ? "Underline"
        : "Block";

  const config: AlacrittyConfig = {
    font: {
      normal: { family: "Maple Mono NF CN" },
      size: 14,
    },
    window: {
      opacity: appearance.backgroundOpacity,
      blur: appearance.backgroundBlur > 0,
      padding: { x: 10, y: 8 },
      decorations: "Transparent",
    },
    cursor: {
      style: {
        shape: cursorShape,
        blinking: appearance.cursorBlink ? "On" : "Off",
      },
    },
    colors: {
      primary: {
        background: colors.background,
        foreground: colors.foreground,
      },
      cursor: {
        text: colors.background,
        cursor: colors.cursor,
      },
      selection: {
        text: colors.selectionForeground,
        background: colors.selectionBackground,
      },
      normal: {
        black: colors.black,
        red: colors.red,
        green: colors.green,
        yellow: colors.yellow,
        blue: colors.blue,
        magenta: colors.magenta,
        cyan: colors.cyan,
        white: colors.white,
      },
      bright: {
        black: colors.brightBlack,
        red: colors.brightRed,
        green: colors.brightGreen,
        yellow: colors.brightYellow,
        blue: colors.brightBlue,
        magenta: colors.brightMagenta,
        cyan: colors.brightCyan,
        white: colors.brightWhite,
      },
    },
    scrolling: {
      history: 100000,
    },
  };

  return `# ============================================
# Claude Den - Alacritty Config
# Theme: ${theme.displayName}
# Generated by claude-den
# ============================================

${toToml(config as unknown as Record<string, unknown>)}`;
}

function toToml(obj: Record<string, unknown> | object, prefix = ""): string {
  const lines: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      lines.push(`[${fullKey}]`);
      for (const [subKey, subValue] of Object.entries(value as Record<string, unknown>)) {
        if (typeof subValue === "object" && subValue !== null && !Array.isArray(subValue)) {
          lines.push("");
          lines.push(...toToml({ [subKey]: subValue }, fullKey).split("\n"));
        } else {
          lines.push(`${subKey} = ${formatTomlValue(subValue)}`);
        }
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function formatTomlValue(value: unknown): string {
  if (typeof value === "string") return `"${value}"`;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return String(value);
  return String(value);
}
