import type { Theme } from "../../types.js";

export function generateGhosttyConfig(theme: Theme): string {
  const { colors, appearance } = theme;

  return `# ============================================
# Claude Den - Ghostty Config
# Theme: ${theme.displayName}
# Generated by claude-den
# Reload: Cmd + Shift + ,
# ============================================

# --- Typography ---
font-family = "Maple Mono NF CN"
font-size = 14
adjust-cell-height = 2

# --- Theme: ${theme.displayName} ---
background = ${colors.background}
foreground = ${colors.foreground}
cursor-color = ${colors.cursor}
selection-background = ${colors.selectionBackground}
selection-foreground = ${colors.selectionForeground}

palette = 0=${colors.black}
palette = 1=${colors.red}
palette = 2=${colors.green}
palette = 3=${colors.yellow}
palette = 4=${colors.blue}
palette = 5=${colors.magenta}
palette = 6=${colors.cyan}
palette = 7=${colors.white}
palette = 8=${colors.brightBlack}
palette = 9=${colors.brightRed}
palette = 10=${colors.brightGreen}
palette = 11=${colors.brightYellow}
palette = 12=${colors.brightBlue}
palette = 13=${colors.brightMagenta}
palette = 14=${colors.brightCyan}
palette = 15=${colors.brightWhite}

# --- Window and Appearance ---
background-opacity = ${appearance.backgroundOpacity}
background-blur-radius = ${appearance.backgroundBlur}
macos-titlebar-style = transparent
window-padding-x = 10
window-padding-y = 8
window-save-state = always
window-theme = auto

# --- Cursor ---
cursor-style = ${appearance.cursorStyle}
cursor-style-blink = ${appearance.cursorBlink}
cursor-opacity = 0.8

# --- Mouse ---
mouse-hide-while-typing = true
copy-on-select = clipboard

# --- Quick Terminal ---
quick-terminal-position = top
quick-terminal-screen = mouse
quick-terminal-autohide = true
quick-terminal-animation-duration = 0.15

# --- Security ---
clipboard-paste-protection = true
clipboard-paste-bracketed-safe = true

# --- Shell Integration ---
shell-integration = zsh

# --- Claude Code Optimizations ---
initial-window = true
quit-after-last-window-closed = true
notify-on-command-finish = always

# --- Performance ---
scrollback-limit = 25000000

# --- Keybindings (Claude Code Workflow) ---
keybind = cmd+d=new_split:right
keybind = cmd+shift+enter=toggle_split_zoom
keybind = cmd+shift+f=toggle_split_zoom
`;
}
