import type { Theme } from "../../types.js";

export function generateStarshipConfig(theme: Theme): string {
  const { colors } = theme;

  return `# ============================================
# Claude Den - Starship Config
# Theme: ${theme.displayName}
# Generated by claude-den
# Place at: ~/.config/starship.toml
# ============================================

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold ${colors.green})"
error_symbol = "[❯](bold ${colors.red})"
vimcmd_symbol = "[❮](bold ${colors.blue})"

[directory]
style = "bold ${colors.blue}"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "bold ${colors.magenta}"
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = " "

[git_status]
style = "bold ${colors.red}"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "="
ahead = "⇡\${count}"
behind = "⇣\${count}"
diverged = "⇕⇡\${ahead_count}⇣\${behind_count}"
untracked = "?\${count}"
stashed = "\\$\${count}"
modified = "!\${count}"
staged = "+\${count}"
deleted = "✘\${count}"

[nodejs]
style = "bold ${colors.green}"
format = "[$symbol($version)]($style) "
symbol = " "

[python]
style = "bold ${colors.yellow}"
format = '[$symbol\${pyenv_prefix}(\${version})]($style) '
symbol = " "

[rust]
style = "bold ${colors.red}"
format = "[$symbol($version)]($style) "
symbol = " "

[golang]
style = "bold ${colors.cyan}"
format = "[$symbol($version)]($style) "
symbol = " "

[cmd_duration]
style = "bold ${colors.yellow}"
min_time = 2_000
format = "[$duration]($style) "
show_milliseconds = false

[line_break]
disabled = false
`;
}
