import type { Theme } from "../../types.js";

export function generateKittyConfig(theme: Theme): string {
  const { colors, appearance } = theme;

  const cursorShape =
    appearance.cursorStyle === "bar"
      ? "beam"
      : appearance.cursorStyle === "underline"
        ? "underline"
        : "block";

  return `# ============================================
# Claude Den - Kitty Config
# Theme: ${theme.displayName}
# Generated by claude-den
# ============================================

# --- Typography ---
font_family      Maple Mono NF CN
font_size        14.0

# --- Theme: ${theme.displayName} ---
background           ${colors.background}
foreground           ${colors.foreground}
cursor               ${colors.cursor}
selection_background ${colors.selectionBackground}
selection_foreground ${colors.selectionForeground}

color0  ${colors.black}
color1  ${colors.red}
color2  ${colors.green}
color3  ${colors.yellow}
color4  ${colors.blue}
color5  ${colors.magenta}
color6  ${colors.cyan}
color7  ${colors.white}
color8  ${colors.brightBlack}
color9  ${colors.brightRed}
color10 ${colors.brightGreen}
color11 ${colors.brightYellow}
color12 ${colors.brightBlue}
color13 ${colors.brightMagenta}
color14 ${colors.brightCyan}
color15 ${colors.brightWhite}

# --- Appearance ---
background_opacity ${appearance.backgroundOpacity}
cursor_shape ${cursorShape}
cursor_blink_interval ${appearance.cursorBlink ? "0.5" : "0"}
hide_window_decorations titlebar-only
window_padding_width 8

# --- Performance ---
scrollback_lines 250000

# --- Keybindings (Claude Code Workflow) ---
map cmd+d launch --location=vsplit --cwd=current
map cmd+shift+enter toggle_layout stack
map cmd+shift+f toggle_layout stack

# --- Shell Integration ---
shell_integration enabled
`;
}
