import type { Theme, TmuxLayout } from "../../types.js";

export const LAYOUTS: ReadonlyMap<string, TmuxLayout> = new Map([
  [
    "coding",
    {
      name: "coding",
      description: "Claude Code left, editor/shell right",
      panes: [
        { command: "claude", split: "horizontal", size: "60%" },
        { command: "$SHELL", split: "vertical" },
      ],
    },
  ],
  [
    "parallel",
    {
      name: "parallel",
      description: "2x2 grid for parallel Claude agents",
      panes: [
        { command: "claude", split: "horizontal", size: "50%" },
        { command: "claude", split: "vertical", size: "50%" },
        { command: "claude", split: "horizontal", size: "50%" },
        { command: "claude", split: "vertical" },
      ],
    },
  ],
  [
    "monitor",
    {
      name: "monitor",
      description: "Claude + logs + git + system monitor",
      panes: [
        { command: "claude", split: "horizontal", size: "60%" },
        { command: "lazygit 2>/dev/null || git log --oneline -20", split: "vertical", size: "50%" },
        { command: "btop 2>/dev/null || top", split: "vertical" },
      ],
    },
  ],
]);

export function generateTmuxConfig(theme: Theme): string {
  const { colors } = theme;

  return `# ============================================
# Claude Den - tmux Config
# Theme: ${theme.displayName}
# Generated by claude-den
# Place at: ~/.tmux.conf
# ============================================

# --- General ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g history-limit 250000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -s escape-time 0
set -g focus-events on

# --- Theme: ${theme.displayName} ---
set -g status-style "bg=${colors.background},fg=${colors.foreground}"
set -g status-left "#[bg=${colors.blue},fg=${colors.background},bold] #S #[default] "
set -g status-right "#[fg=${colors.brightBlack}]%H:%M #[fg=${colors.magenta}]#h "
set -g status-left-length 30
set -g status-right-length 50

setw -g window-status-format "#[fg=${colors.brightBlack}] #I:#W "
setw -g window-status-current-format "#[bg=${colors.blue},fg=${colors.background},bold] #I:#W "

set -g pane-border-style "fg=${colors.brightBlack}"
set -g pane-active-border-style "fg=${colors.blue}"
set -g message-style "bg=${colors.yellow},fg=${colors.background}"

# --- Keybindings ---
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Split panes (Claude Code workflow)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Navigate panes with Alt+arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Reload config
bind r source-file ~/.tmux.conf \\; display "Config reloaded!"

# New window in current path
bind c new-window -c "#{pane_current_path}"
`;
}

export function generateTmuxLayoutScript(layout: TmuxLayout): string {
  const sessionName = `den-${layout.name}`;
  const lines = [
    "#!/usr/bin/env bash",
    `# Claude Den Layout: ${layout.name} - ${layout.description}`,
    "",
    `SESSION="${sessionName}"`,
    "",
    "# Kill existing session if any",
    `tmux has-session -t $SESSION 2>/dev/null && tmux kill-session -t $SESSION`,
    "",
    "# Create new session",
    `tmux new-session -d -s $SESSION -x $(tput cols) -y $(tput lines)`,
    "",
  ];

  for (let i = 0; i < layout.panes.length; i++) {
    const pane = layout.panes[i];
    if (i > 0) {
      const splitFlag = pane.split === "horizontal" ? "-h" : "-v";
      const sizeFlag = pane.size ? `-p ${parseInt(pane.size)}` : "";
      lines.push(`tmux split-window ${splitFlag} ${sizeFlag} -t $SESSION`);
    }
    lines.push(`tmux send-keys -t $SESSION '${pane.command}' Enter`);
    lines.push("");
  }

  lines.push("# Select first pane");
  lines.push(`tmux select-pane -t $SESSION:0.0`);
  lines.push("");
  lines.push("# Attach to session");
  lines.push(`tmux attach-session -t $SESSION`);

  return lines.join("\n");
}
